//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrackItDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CourseGroupMap
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CourseGroupMap()
        {
            this.Activities = new HashSet<Activity>();
        }
    
        public int CGId { get; set; }
        public Nullable<int> CourseId { get; set; }
        public Nullable<int> GroupId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Activity> Activities { get; set; }
        public virtual Course Course { get; set; }
        public virtual GroupTable GroupTable { get; set; }
    }
}
