//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrackItDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class FacultyGroup
    {
        public int FGId { get; set; }
        public Nullable<int> FacultyId { get; set; }
        public Nullable<int> GroupId { get; set; }
    
        public virtual Faculty Faculty { get; set; }
        public virtual GroupTable GroupTable { get; set; }
    }
}
